AWSTemplateFormatVersion: 2010-09-09

Description: CloudProject07:04

Parameters:

  VPCStackParameter:
    Type: String
    Description: "Name of VPC stack to build on"

  VPCRegionParameter:
    Type: String
    Description: VPC Region

  NginxAZParameter:
    Type: String
    Description: Nginx server Availability Zone

  Amz2AmiIdParameter:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  EC2KeyParameter:
    Type: String
    Description: "EC2 key name"

  SSHKeyParameter:
    Type: String
    Description: "Git key pair name"

  NginxTypeParameter:
    Type: String
    Description: "Nginx server instance type"

Resources:

  EC2S3Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2S3Profile
      Roles:
        - FilesBucketRole

  EC2Instance:
    Type: AWS::EC2::Instance
    DeletionPolicy: Delete
    Properties: 
      AvailabilityZone: !Ref NginxAZParameter
      ImageId: !Ref Amz2AmiIdParameter
      InstanceType: !Ref NginxTypeParameter
      KeyName: !Ref EC2KeyParameter
      Monitoring: True
      NetworkInterfaces:
      - DeviceIndex: 0
        SubnetId: {"Fn::ImportValue" : !Sub "${VPCStackParameter}-PublicSubnet1Id"}
        GroupSet:
          - {"Fn::ImportValue" : !Sub "${VPCStackParameter}-SG-WebPublicId"}
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            yum update -y
            rpm --import https://packages.microsoft.com/keys/microsoft.asc
            rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
            amazon-linux-extras enable nginx1
            yum clean metadata
            yum install -y git amazon-efs-utils nginx
            yum install -y aspnetcore-runtime-3.1 dotnet-sdk-3.1
            yum install -y libunwind mssql-cli unixODBC-devel
            systemctl enable nginx
            systemctl start nginx
        
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> /home/ec2-user/.ssh/known_hosts
            cat << EOF > /home/ec2-user/.ssh/config
            Host github.com
              HostName github.com
              IdentityFile /home/ec2-user/.ssh/${SSHKeyParameter}
            EOF
            chmod 400 /home/ec2-user/.ssh/config
            aws s3 cp s3://${VPCStackParameter}.files/gitpull.sh /home/ec2-user/gitpull.sh
            chown -R ec2-user.ec2-user /home/ec2-user
            
      IamInstanceProfile: "EC2S3Profile"
      Tags: 
      - Key: Name
        Value: !Sub '${VPCStackParameter}-NginxServerForAMI'
    DependsOn: EC2S3Profile 


Outputs:

  EC2S3ProfileArn:
    Description: EC2S3ProfileArn
    Value: !GetAtt EC2S3Profile.Arn
    Export:
      Name: !Sub '${VPCStackParameter}-EC2S3Arn'
