AWSTemplateFormatVersion: 2010-09-09

Description: CloudProject07:08

Parameters:

  DomainNameParameter:
    Type: String
    Description: "Project domain name"
    
  HostedZoneIdParameter:
    Type: String
    Description: "Domain zone ID"

Resources:

  WWWCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'www.${DomainNameParameter}'
      DomainValidationOptions:
        - DomainName: !Sub 'www.${DomainNameParameter}'
          HostedZoneId: !Ref HostedZoneIdParameter
      ValidationMethod: DNS

  APICertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'api.${DomainNameParameter}'
      DomainValidationOptions:
        - DomainName: !Sub 'api.${DomainNameParameter}'
          HostedZoneId: !Ref HostedZoneIdParameter
      ValidationMethod: DNS

  WWWDevCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'wwwdev.${DomainNameParameter}'
      DomainValidationOptions:
        - DomainName: !Sub 'wwwdev.${DomainNameParameter}'
          HostedZoneId: !Ref HostedZoneIdParameter
      ValidationMethod: DNS

  APIDevCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'apidev.${DomainNameParameter}'
      DomainValidationOptions:
        - DomainName: !Sub 'apidev.${DomainNameParameter}'
          HostedZoneId: !Ref HostedZoneIdParameter
      ValidationMethod: DNS
